// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyE83mU-sC7xT-uavcV5pdtVFQjX7Eb44',
    appId: '1:723491416190:web:df32c4f885bf92c3b4102f',
    messagingSenderId: '723491416190',
    projectId: 'store-app-1a86f',
    authDomain: 'store-app-1a86f.firebaseapp.com',
    storageBucket: 'store-app-1a86f.firebasestorage.app',
    measurementId: 'G-CPY41FJJGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS2Md047U2M92Qc49p9eTJF9dCRjWbWaQ',
    appId: '1:723491416190:android:516b6bfd6b69e6b6b4102f',
    messagingSenderId: '723491416190',
    projectId: 'store-app-1a86f',
    storageBucket: 'store-app-1a86f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcgobRKZl_P9fbcvrdj5VBtrMVgzHehGE',
    appId: '1:723491416190:ios:caf7c9b9abe8da84b4102f',
    messagingSenderId: '723491416190',
    projectId: 'store-app-1a86f',
    storageBucket: 'store-app-1a86f.firebasestorage.app',
    iosClientId: '723491416190-8ebeg63ai8213u3ld4456o1v3374fel0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcgobRKZl_P9fbcvrdj5VBtrMVgzHehGE',
    appId: '1:723491416190:ios:caf7c9b9abe8da84b4102f',
    messagingSenderId: '723491416190',
    projectId: 'store-app-1a86f',
    storageBucket: 'store-app-1a86f.firebasestorage.app',
    iosClientId: '723491416190-8ebeg63ai8213u3ld4456o1v3374fel0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyE83mU-sC7xT-uavcV5pdtVFQjX7Eb44',
    appId: '1:723491416190:web:81d079b0b798e440b4102f',
    messagingSenderId: '723491416190',
    projectId: 'store-app-1a86f',
    authDomain: 'store-app-1a86f.firebaseapp.com',
    storageBucket: 'store-app-1a86f.firebasestorage.app',
    measurementId: 'G-Y8G13TEWEC',
  );

}